### PR TITLE
update-fonts

### PR DESCRIPTION
**Pull request by ba314**

### CODE REVIEW

**Comment by retifrav** [comment]
I prefer not to use external resources (styles, fonts, scripts), so everything is stored locally.
SVG is actually a good idea, although it fits wrong in 540px example. But for 1080px it's great.

**Comment by ba314** [comment]
Local fonts. SVG size fix.

**Comment by retifrav** [comment]
Didn't know about `background-size: contain;`, nice thing, I'll merge it and .svg.
But what's the point of adding so many fonts and specifying their weight and style (_I am really not a frontender, as you can tell_)?

**Comment by ba314** [comment]
Better browser support - https://css-tricks.com/snippets/css/using-font-face/

**Comment by retifrav** [comment]
Thanks, merged.
Also accidentally pushed it to your branch :)

**Pull request merged**
